# 1. Надо написать чтение этого конфига и передачу его в другие модули
# 2. Нужно сделать возможность в классе конфига доступа к вложенным секциям через точку в ключе (примеры будут ниже)
# 3. [опицонально] Нужно сделать передачу конфига в классы желательно в бэкграунде (чтобы передача была незаметна)
# 4. Если значение начинается с $, то его нужно получать из переменной окружения

# Конфиг:

web:
  port: 443
  hostname: my-test.projects.me

telegram:
  token: $BOT_TOKEN
  username: mybot

db:
  hosts:
    - db.host.1:5432
    - db.host.2:5432
    - db.host.3:5432
  username: admin
  password: $BD_PASSWORD
  dbname: my_db


# Пример:
# (bash) export BD_PASSWORD=12345
# (python) config['db.password']
#             out >> 12345
# (python) config['db']
#             out >> {'hosts': [...], 'username': 'admin', ...}
# 



# 3-ий пункт можно не делать, он больше уже на знание паттернов и некоторых библиотек, можно просто предложить варианты реализации такого исполнения.